globals:
  Terminal: true
  VirtualMachine: true

env:
  browser: true
  es6: true
extends: 'eslint:recommended'
rules:
  linebreak-style:
    - error
    - unix
  indent:
    - error
    - 4
    - SwitchCase: 1
  brace-style:
    - error
    - stroustrup
  quotes:
    - error
    - single
  semi:
    - error
    - always
